---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - '**'
      - '!.github/**'
      - '!.*'
      - '!tox.ini'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Action Testing"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 4
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Run Action: ${{ github.repository }} [valid package]"
        uses: ./
        with:
          index_url: https://test.pypi.org/simple
          package_name: ITR

      - name: "Run Action: ${{ github.repository }} [valid package/version]"
        uses: ./
        with:
          index_url: https://test.pypi.org/simple
          package_name: ITR
          package_version: 1.1.10

      # Note: test when version string prefixed with a "v" character
      - name: "Run Action: ${{ github.repository }} [valid package/version]"
        uses: ./
        with:
          index_url: https://test.pypi.org/simple
          package_name: ITR
          package_version: v1.1.10

      # yamllint disable-line rule:line-length
      - name: "Run Action: ${{ github.repository }} [valid package/invalid version]"
        uses: ./
        with:
          index_url: https://test.pypi.org/simple
          package_name: ITR
          package_version: 13.69.666

      # yamllint disable-line rule:line-length
      - name: "Run Action: ${{ github.repository }} [valid package/development version]"
        uses: ./
        with:
          index_url: https://test.pypi.org/simple
          package_name: osc-github-devops
          package_version: 0.1.22.dev1
          pre_release: "true"

      # Check for invalid package and version
      - name: "Run Action: ${{ github.repository }} [invalid package/version]"
        uses: ./
        with:
          index_url: https://test.pypi.org/simple
          package_name: ITR-random-thing
          package_version: 13.69.666

      # Check a non-functioning/resolving repository URL
      - name: "Run Action: ${{ github.repository }} invalid repo [FAILURE]"
        uses: ./
        # Deliberately testing for failure
        continue-on-error: true
        with:
          # Invalid top-level domain will never resolve
          index_url: https://non.existent.ogfdhfdgrg/
          package_name: gremlin
          package_version: 13.69.666

      # Not querying pre-releases, expected to fail
      # yamllint disable-line rule:line-length
      - name: "Run Action: ${{ github.repository }} pre-releases not requested [FAILURE]"
        uses: ./
        # Deliberately testing for failure
        continue-on-error: true
        with:
          index_url: https://test.pypi.org/simple
          package_name: osc-github-devops
          package_version: 0.1.22.dev1
          exit_on_fail: "true"

      # Check for invalid package and version
      # yamllint disable-line rule:line-length
      - name: "Run Action: ${{ github.repository }} invalid package/version [FAILURE]"
        uses: ./
        # Deliberately testing for failure
        continue-on-error: true
        with:
          index_url: https://test.pypi.org/simple
          package_name: ITR-random-thing
          package_version: 13.69.666
          exit_on_fail: "true"
